# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04481ff92b730dd36ab119eb660cb138e568b1906575f26fc5849e651b61c6fe3b53ec53b1690e4f1d0b97d3265ab14c7073e0abce03b0b83577f7c41e99ae14

test:
  secret_key_base: ed7a12aa0f326db38ed52527b4c1bd39e764833a8d93218d2b5762ede13c66712f5ce0d4e130c8d87b9460f4daf6d9c2651e293b05c231a17786dc98363db6e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
